### ISSUE TITLE
Programs are not rendering in the skills section on mobile (plus minor UXI issues)

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#10]
- [x] Course providers not rendering on mobile
- [x] Back button not working to get back to initial state
- [x] Background not rendering correctly / has faint stripes overlaying either side of the screen

![image](https://user-images.githubusercontent.com/16677332/90083783-80825980-dce1-11ea-95fd-5ee19681d80c.png)

**Comment by jferragut** [comment]
@newtporter first 2 were addressed in a recent pr. Are you seeing the lines in prod or dev?

**Comment by jferragut** [comment]
Pr of note : https://github.com/miamiworks/web/pull/22

**Comment by jferragut** [comment]
just fixed the mobile background
