### ISSUE TITLE
Downloadable content modal is cutoff on mobile

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#12]
Download modals are cutoff on mobile
![image](https://user-images.githubusercontent.com/16677332/90083873-b4f61580-dce1-11ea-8c7d-2bacd6b51aeb.png)

**Comment by jferragut** [comment]
@newtporter  as per our discussion, the guide section is commented out now so we aren't using it currently. Regarding the other modals, they have been resolved in previous pr. closing this issue.
