### ISSUE TITLE
Downloadable content is not connected in the skills and resources sections

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#13]
- [x] the different syllabuses are the same across programs at the moment
- [x] the job search field guide resource does not download at the moment

**Comment by jferragut** [comment]
@berno0  added `skill_pathways` collection to db.

I am working on the following
- [x] add rules
- [x] add request to init in context
- [ ] add data variables to views in key skills

**Comment by jferragut** [comment]
This is fixed. closing
