### ISSUE TITLE
Resources sub-section below events should be commented out

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#15]
The field guide is still in review and won't be ready for the launch. We need to comment out the second portion of the Events & Resources section until this is ready (expected on Friday). 
![image](https://user-images.githubusercontent.com/16677332/90085260-8c701a80-dce5-11ea-9457-606135edc3f3.png)

**Comment by jferragut** [comment]
@newtporter comment the entire section in the picture?

**Comment by jferragut** [comment]
done
