### ISSUE TITLE
Legal footer link update

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#16]
Legal in the footer needs to link to https://www.beaconcouncil.com/terms-conditions/

**Comment by newtporter** [comment]
@berno0

**Comment by jferragut** [comment]
@newtporter is @berno0 handling this or should we?

**Comment by berno0** [comment]
@jferragut  you guys should. Its just adding a link to the MDBC terms and privacy. 
Below is the link:
https://www.beaconcouncil.com/terms-conditions/

**Comment by jferragut** [comment]
@berno0 on it

**Comment by jferragut** [comment]
Done
