### ISSUE TITLE
Programs are not passing through the program id on form submissions

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#18]
Programs are not passing through the program id on form submissions. This data is required to trigger email updates to each program_contact_email once users submit interest in a syllabus. 

Notice the programs column and top of the collection on the right use the same ID
![image](https://user-images.githubusercontent.com/16677332/90087529-0787ff80-dceb-11ea-839e-b66c9cd2b2d2.png)

**Comment by newtporter** [comment]
@berno0 can clarify how to access the program id so we can ensure emails are sent out after successful submissions.

**Comment by jferragut** [comment]
@berno0 can you elaborate on this? I don't see the ID on the data. Are you referring to the document id in firebase?

**Comment by berno0** [comment]
@jferragut 

    FirebaseDB.collection("programs")
      .get()
      .then(querySnapshot => {
        const data = querySnapshot.docs.map((doc) => {
          return { id: doc.id, ...doc.data() }
        })

**Comment by jferragut** [comment]
@berno0 that is what I thought you meant. I will pass the doc id. Thanks!

**Comment by jferragut** [comment]
Done.
<img width="564" alt="Screen Shot 2020-08-12 at 11 02 53 PM" src="https://user-images.githubusercontent.com/31458614/90089719-14f3b880-dcf0-11ea-8503-3d242aace8cd.png">
