### ISSUE TITLE
Connect the Apply now CTAs in the skills section to the proper table in Firebase

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#28]
re-read the issue title if you're unsure what to do ;)

**Comment by newtporter** [comment]
@berno0 the links have been added and are in the last column of the Google sheet

**Comment by berno0** [comment]
@newtporter  @alesanchezr  I reviewed this issue yesterday, and the data you need is in Firebase Firestore. Not sure if I am missing anything in this issue but it seems like a front-end thing.

**Comment by newtporter** [comment]
Confirmed data is updated in Firebase. @jferragut can you connect these CTAs so they links work?
