### ISSUE TITLE
skill_pathways only display program views for a 4 card layout

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#30]
Currently all programs display in a 4 program card size rather than a responsive state for fewer cards. 

[Here is the Figma frame](https://www.figma.com/file/6SMBgAOsrFc0Vf4oUnDsSe/MiamiTech.Works?node-id=121%3A423) with the 2 card layout. 

_Note: there remain some additional tweaks to program layouts to accommodate situations with more than 4 programs._

**Comment by alesanchezr** [comment]
This is @jferragut 's realm.
