### ISSUE TITLE
Add Fixed-Top navigation to the site

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#33]
[Design for desktop](https://www.figma.com/file/6SMBgAOsrFc0Vf4oUnDsSe/MiamiTech.Works?node-id=485%3A0)
[Design for mobile](https://www.figma.com/file/6SMBgAOsrFc0Vf4oUnDsSe/MiamiTech.Works?node-id=499%3A5701)

**Comment by alesanchezr** [comment]
@mberrio10 Do you want to try this???

**Comment by mberrio10** [comment]
so you guys want that navbar to stay with the user while they scroll thru the site? 
because that is not sticky is called Fixed-Top
![image](https://user-images.githubusercontent.com/39283177/90279666-a28df000-de37-11ea-815e-e491cc3958be.png)

**Comment by newtporter** [comment]
Hey @mberrio10 , sorry I missed your comment. Feel free to tag me so I don't miss it moving forward. 

**Yes Fixed-Top navigation, with the modified styling seen in the Figma** 

Side note: [Sticky Nav](https://www.w3schools.com/howto/howto_css_fixed_menu.asp) would mean if it wasn't at the top to begin with and then locked there past a certain point on the page, right?

**Comment by mberrio10** [comment]
navbar is now fixed-sticky
