### ISSUE TITLE
Compressing an Image before Uploading it to Firebase Storage

### ISSUE THREAD

**Issue by alesanchezr** [miamiworks/web#34]
Images on the firebase hosting are very heavy (2 MB avg) I know we can use algorithms to reduce them to about 150kb per image (for the big ones) and maybe 5kb for the small ones.

That will increase website performance dramatically.

@newtporter is this the right repository for this? Or the backend team uses a different one?

**Comment by berno0** [comment]
@alesanchezr @newtporter  we implemented a firebase function to resize and compress images on 8/14/20 both events and logos have been compressed and resized. The ones we are missing are the program background images that I am waiting on @alesanchezr  to provide the size he needs.

**Comment by berno0** [comment]
As per @alesanchezr  we are rezising this images to 300x150.

**Comment by berno0** [comment]
@alesanchezr @newtporter  created function to compress and resize program images to 300x150 and skill pathway images to 250x450. The images look grainy. How should we proceed?
