### ISSUE TITLE
Ensure events with incomplete data do not display on the site

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#40]
This may be because the database has placeholder text in some of the fields or we are not properly filtering what's to be displayed. 
![image](https://user-images.githubusercontent.com/16677332/90402231-241a9380-e06d-11ea-9939-a0c58f460921.png)

**Comment by berno0** [comment]
@alesanchezr @newtporter  This is not back-end.

**Comment by alesanchezr** [comment]
Sometimes you are returning NaN as a data-type and sometimes you are returning NaN as a string, i'm checking for both now.
