### ISSUE TITLE
Add a CTA to the skills section below the core component to talk to someone

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#45]
The skills section can  be overwhelming we should consider an option for users who want to talk to a person. 

Don't know your skill?
will route to coaching for finding career advice
(in the future will add a self-assessment)

**Comment by jferragut** [comment]
@newtporter is this to be implemented or should i pause and backlog it for now?

**Comment by newtporter** [comment]
@jferragut backlog it for now. We need to determine who will field these sorts of coaching requests. Related: https://github.com/miamiworks/web/projects/1#card-43815128

**Comment by jferragut** [comment]
done
