### ISSUE TITLE
Jobs section improvements on the home page

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#46]
- [x] Remove blue border on job tags
- [x] Juxtapose jobs carousel so no adjacent jobs have the same company and/or tag

**Comment by jferragut** [comment]
>     * Juxtapose jobs carousel so no adjacent jobs have the same company and/or tag

@newtporter can you elaborate on this?

**Comment by newtporter** [comment]
No two subsequent cards should either have the same (1) Company Name or (2) skill_pathway tag
