### ISSUE TITLE
Create hover state for skill_pathway categories in the skills section on the home page

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#48]
![image](https://user-images.githubusercontent.com/16677332/90453421-98c9ee00-e0be-11ea-9a1e-4adc26103c4b.png)

**Comment by jferragut** [comment]
@newtporter is the expected behavior to mimic the active state?

**Comment by newtporter** [comment]
I could see a few different options for hover:

1. Grey-White (in between the two) text change in between the resting state and hover state
2. Grey underline of resting state
3. Combo of 1 + 2

**Comment by newtporter** [comment]
@jferragut go ahead and make it white for the hover state (Jay's guidance).

**Comment by jferragut** [comment]
> @jferragut go ahead and make it white for the hover state (Jay's guidance). 

@newtporter With bold, bold and underline, or just the color change?

**Comment by jciesluk** [comment]
@newtporter @jferragut - I think I'm more into the subtle just color change.. Is there a way to test it out on your end without being too cumbersome? If so, I can experiment in Figma tmrw

**Comment by newtporter** [comment]
@jciesluk let's go with just the color change to white. 

@jferragut the resting/default state for the skill_pathway categories should be Dark Grey `#CACACA` . It looks like it's white right now so the hover state won't show until properly until that's updated.

**Comment by jferragut** [comment]
@newtporter  on it.
