### ISSUE TITLE
Update Events section styling of the home page to match design styling

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#52]
[Google Drive Icons](https://drive.google.com/drive/folders/10j3dMHYYxMFJjlk3hXlRIETQh8S4y-TG?usp=sharing) and [Figma File](https://www.figma.com/file/6SMBgAOsrFc0Vf4oUnDsSe/MiamiTech.Works?node-id=129%3A0)

- [ ] Icon update
- [ ] Font colors 

Note: we should not have black anywhere. We should have Dark Blue (#171838) to replace it throughout the site. Design style wiki coming soon.

Design File
![image](https://user-images.githubusercontent.com/16677332/90455512-3e339080-e0c4-11ea-83f3-ea31e038beea.png)
Production Version 
![image](https://user-images.githubusercontent.com/16677332/90455523-45f33500-e0c4-11ea-86f6-b699990d0c0f.png)

**Comment by alesanchezr** [comment]
This icon is paid, dont have access @newtporter. That is why we choose the other one. 😢 

@mberrio10 are you going to fix this color thing?

**Comment by mberrio10** [comment]
yes got it :) 👍

**Comment by mberrio10** [comment]
hi! @newtporter, I am doing the changes. The color that you wrote on the notes (#171838) is not the same as the one in Figma which is (#282A62) that is the image you shared, do you still want me to set it as (#171838)?

**Comment by mberrio10** [comment]
text is now Blue #282A62
