### ISSUE TITLE
Redesign career coaching section of the home page 

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#54]
Consider how we differentiate coaching types:
1. Job search advice
2. Discovering career paths/what to do

We're catering towards the (1) use case right now, but not (2) which is important to our partners providing course offerings and more importantly to many job seekers looking for a career pivot and unsure how/where to start. 

**Cari**
> Redesign career coaching module to filter by: Name, last name, email, phone number, year of experience in tech (0, 1-5, 5-10, 10+), are you currently employed (yes or no). Wyncode will also put forth career coaches so maybe delete the Dougs pictures and add logos or general pic describing the benefits of coaching sessions. 

- [x] Design complete
- [ ] Frontend complete

**Comment by jciesluk** [comment]
I will review and refine this section tomorrow and hopefully have something for you by night. Does that work @newtporter ?

**Comment by newtporter** [comment]
@jciesluk sounds good, thanks!

**Comment by jciesluk** [comment]
@newtporter - are we looking to add a filter for the "career pivoter/student" in this section? I noticed the comment underneath the initial and wasn't sure

**Comment by jciesluk** [comment]
<img width="737" alt="Screen Shot 2020-08-19 at 10 18 35 PM" src="https://user-images.githubusercontent.com/47903294/90709336-f3537d80-e269-11ea-890b-0c65a7b1bd3f.png">

**Comment by jciesluk** [comment]
@newtporter - what about something like this? It's sort of rough, but do you think it works? It's in the coloring book on Figma. I was trying to keep it consistent with Events and Resources section.
