### ISSUE TITLE
Add the post a job button to the navigation and connect it to the submission function

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#55]
@berno0 is finishing up the first version of the job submission functionality. 

Here is the button for reference (you can find it in the Figma file)
![image](https://user-images.githubusercontent.com/16677332/90657866-e5254300-e210-11ea-8a74-c85358a67d96.png)

**Comment by berno0** [comment]
@newtporter  Yes, working on that today with Fidel. Should have an MVP ready by the end of day. It will be hosted on a separate project called miami-works-jobs with the domain jobs.miamitech.works.

**Comment by berno0** [comment]
@newtporter @alesanchezr  this is a front-end issue.

**Comment by newtporter** [comment]
@mberrio10 I think that @jferragut created this when we went through the top navigation the first time (it may be commented out though). Can you add this to your updated navigation (#33 )? FYI @alesanchezr
