### ISSUE TITLE
Pictures on skills_pathways should change should change for each category

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#56]
These should be pulling from the `skill_pathways` collection in Firebase. 

@berno0 I noticed the `Image_URL` is a Google Drive link. Not sure if these should be hosted in Firebase and compressed as we discussed doing with the other images.

**Comment by berno0** [comment]
@newtporter  That is a legacy field that we kept. We probably would delete moving forward. In any of the collections if images are referenced is always by the field that ends in **_path**. So for the collection skill_pathways the image reference is **image_file_path**. Alejandro is using that to reference firebase storage.
