### ISSUE TITLE
Names of programs on skills_pathways must not be cut off

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#57]
@miamiworks/design  do you want to wrap these or how do you want @miamiworks/frontend to proceed? 

Please keep in mind this related issue #30 (different layout options for 2, 3 and 4+ program options). 

![image](https://user-images.githubusercontent.com/16677332/90660444-ea37c180-e213-11ea-86ac-6d35720bef34.png)

**Comment by crys11** [comment]
I think it would be better to just increase the width of each box and just display three. Might end up having a little bit more margin depending on the width but it would be better to read.
