### ISSUE TITLE
Admins/Contact Person not receiving emails for form submissions 

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#58]
**Cari**
> The admin of each skill pathway (GA, Wyncode, MDC, etc) do not receive an automated email when someone downloads the syllabus.

FYI @berno0. Probably worth confirming with @jferragut to see if the form is passing the program through on submission (which I believe impacts the mail trigger in Firebase).

**Comment by berno0** [comment]
@newtporter We are working on updating the function. We have another issue opened that request for the program name and time of submission to be added.

**Comment by berno0** [comment]
@newtporter Currently doing it manually with Cari, but we should have it automated by today.

**Comment by berno0** [comment]
Done. Tested with Cari and she confirmed the format is good.
