### ISSUE TITLE
Jobs cards on desktop have several rendering issues for longer strings and some minor UX issues

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#7]
- [ ] Job cards are wonky with longer titles and are not displaying properly.
- [ ] The cards are also not clickable to view the posting (the entire card space should be clickable.
- [ ] Tags do not function / toggle views (we may want to kill these for the MVP)
![image](https://user-images.githubusercontent.com/16677332/90083555-e02c3500-dce0-11ea-8dfa-71d95b147afd.png)

**Comment by alesanchezr** [comment]
@newtporter how are we going to fix the titles?
