### ISSUE TITLE
logo on mobile (Samsung S9) not vertically centered.

### ISSUE THREAD

**Issue by berno0** [miamiworks/web#70]
This issue has been fixed for iPhone 8, but its still a problem on a Samsung S9.

**Comment by jferragut** [comment]
@berno0 can you check again? we pushed a PR for the mobile menu. If this is still not fixed, can you share a screenshot of the behavior ?

**Comment by alesanchezr** [comment]
@berno0 can you check?

**Comment by berno0** [comment]
@jferragut @alesanchezr  its still not vertically align on the Samsung S9, overflows downwards. I do see the fix for the iPhone 8. Has this been fix after the 11:33 AM deployment to firebase?

**Comment by berno0** [comment]
![Screenshot_20200826-125242_Chrome.jpg](https://user-images.githubusercontent.com/16947858/91333077-18307f00-e79b-11ea-9e11-8b153e6db7d4.jpg)
