### ISSUE TITLE
Data is not displaying in the skills section (or has yet to be connected) and logos are not loading properly

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#8]
- [x] Summary data not yet linked - available in the #content channel in Slack. 
- [x] Note count of local providers should be variable based on course providers in the Db. (number just above the section CTA)
![image](https://user-images.githubusercontent.com/16677332/90083687-39946400-dce1-11ea-95ec-e03a466ca306.png)

- [x] Course provider logos are not rendering
![image](https://user-images.githubusercontent.com/16677332/90083706-45802600-dce1-11ea-8533-84711c9f499b.png)

- [x] Course descriptions are not yet added. 
- [x] Logos are not rendering.
![image](https://user-images.githubusercontent.com/16677332/90083732-5335ab80-dce1-11ea-8112-6e3d872d52d4.png)

**Comment by newtporter** [comment]
@jferragut the content for the initial state of each skill pathway can be found in the new firebase collection (will be up shortly)

**Comment by jferragut** [comment]
@newtporter this was finished in https://github.com/miamiworks/web/pull/22
