### ISSUE TITLE
Update the copy in the coaching section

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#81]
**Want to break into tech?**
Talk to our career coaches for free. 
Our mentors have practical experience helping people for all walks of life switch to jobs in tech. 

**Looking for a new tech job?**
Already in tech and need a new job?
Talk to specialized career coaches to hear opportunities that fit your profile.
Our mentors will go through the job searching process with you 1-1.

**Comment by jferragut** [comment]
@newtporter are we replacing the 2 sub sections in the pic below?
<img width="1159" alt="Screen Shot 2020-08-28 at 4 29 03 PM" src="https://user-images.githubusercontent.com/31458614/91612538-a481a400-e94b-11ea-8e17-e6b67dbdc9a0.png">

also, the bold I am assuming is the `h3`, will the next line on each be the `h4` or are we removing `h4` all together?
