### ISSUE TITLE
Jobs section gallery view

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#83]
We've received feedback where users are not sure how to scroll through events/jobs on the home page to access more jobs. Suggested update:

Jobs: convert with a gallery view with a CTA to the dedicated jobs page. [Figma Design](https://www.figma.com/file/6SMBgAOsrFc0Vf4oUnDsSe/MiamiTech.Works?node-id=186%3A4597) 
![image](https://user-images.githubusercontent.com/16677332/92532422-4338bb00-f1fe-11ea-9329-db21582027d2.png)

**Comment by alesanchezr** [comment]
Amazing, I agree.

**Comment by newtporter** [comment]
@jciesluk do you have some time to give some guidance on these issues this week?

**Comment by jciesluk** [comment]
> @jciesluk do you have some time to give some guidance on these issues this week?
> 
> _edit: we ran with modifications to your previous job card design layout_

@newtporter Yes I can look at this tonight or tomorrow after work. Do you want to connect via call on this?
