### ISSUE TITLE
Connect Webflow Frontend with Firebase

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#85]
[miamiworks.webflow (4).zip](https://github.com/miamiworks/web/files/5204334/miamiworks.webflow.4.zip)
Areas/modifications to note:

- [ ] Accounting for companies without a logo

**Comment by alesanchezr** [comment]
[miamiworks.webflow (4).zip](https://github.com/miamiworks/web/files/5204329/miamiworks.webflow.4.zip)
@KJCastillo this is the latest one, ignore the other one please!

**Comment by KJCastillo** [comment]
understood!
