### ISSUE TITLE
Directly accessing the dedicated jobs page does not work

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#92]
https://miamitech.works/jobs

A new user landing directly on the jobs page won't be able to see anything. @berno0 believes this may be an issue with how authentication is being done. @alesanchezr

**Comment by alesanchezr** [comment]
I was able to fix the error but I think it has something to do with the data (but i'm not sure yet), form some reason the dates are coming different, some times its imposible to parse the date using the dayjs library.
