### ISSUE TITLE
Events in the past should not display in the right column on the jobs page

### ISSUE THREAD

**Issue by newtporter** [miamiworks/web#93]
- [ ] Events in the past (before today) should not display in the right column 
- [ ] Events should not display unless there is a registration link 
@alesanchezr FYI - screenshot taken 9/29
![image](https://user-images.githubusercontent.com/16677332/94583854-f15ae200-024b-11eb-9edc-02c2bbb0ac2f.png)

**Comment by alesanchezr** [comment]
That is more like a backend thing, I'm asking for sorted events but they are sorting like dates are words intead of dates.
